# fly.toml file generated for your-app-name on 2023-10-27T12:00:00-04:00

app = "eurobond_inventory"
primary_region = "sin" # Singapore is a good choice for India

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source="app_data"
  destination="/data"